# HYPRLAND SPECIFIC
XDG_CURRENT_DESKTOP=Hyprland
XDG_SESSION_TYPE=wayland
XDG_SESSION_DESKTOP=Hyprland

# NECESSARY FOR ARCH WITH SSH AGENT & VSCODE
SSH_AUTH_SOCK=$XDG_RUNTIME_DIR/ssh-agent.socket
SSH_AGENT_SOCK=$SSH_AUTH_SOCK

# GTK SETTINGS
GTK_USE_PORTAL=1
GDK_DEBUG=portals
GTK_THEME=catppuccin-frappe-sapphire-standard+default

# QT SETTINGS
QT_SCALE_FACTOR=1

# INPUT
QT_IM_MODULE=fcitx
XMODIFIERS=@im=fcitx
SDL_IM_MODULE=fcitx
GLFW_IM_MODULE=ibus

# EDITOR
EDITOR="/usr/bin/nvim"
VISUAL=nvim

# GBA DEVTOOLS
DEVKITPRO="/opt/devkitpro"
DEVKITARM="/opt/devkitpro/devkitARM"
DEVKITPPC="/opt/devkitpro/devkitPPC"

# FNM + RUBY
PATH=/home/nexus/.local/share/fnm:$PATH
PATH=/opt/cisco/anyconnect/bin:$PATH
PATH=/home/nexus/.local/bin:$PATH
GEM_HOME=$(gem env user_gemhome)
PATH=$PATH:$GEM_HOME/bin

# PERL
PATH=$PATH:$HOME/perl5/bin
PATH="$HOME/perl5/bin${PATH:+:${PATH}}"
PERL5LIB="$HOME/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"
PERL_LOCAL_LIB_ROOT="$HOME/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"
PERL_MB_OPT="--install_base \"$HOME/perl5\""
PERL_MM_OPT="INSTALL_BASE=$HOME/perl5"

# PGSQL
LD_LIBRARY_PATH=/usr/local/pgsql/lib
PATH=/usr/local/pgsql/bin:$PATH

# GO PATH and BIN
GOPATH=$HOME/dev/go
GOBIN=/usr/local/go/bin
PATH=$PATH:$GOBIN:$GOPATH/bin

# RUST - CARGO BIN
PATH=$HOME/.cargo/bin:$PATH

# .local BIN
PATH=$HOME/.local/bin:$PATH
