SSH_AUTH_SOCK=${XDG_RUNTIME_DIR}/ssh-agent.socket
SSH_AGENT_SOCK=${SSH_AUTH_SOCK}
PATH=${HOME}/.local/bin:${PATH}

GTK_USE_PORTAL=1
GDK_DEBUG=portals
GTK_THEME=catppuccin-frappe-sapphire-standard+default

QT_SCALE_FACTOR=1

QT_IM_MODULE=fcitx
XMODIFIERS=@im=fcitx
SDL_IM_MODULE=fcitx
GLFW_IM_MODULE=ibus
