general {
    lock_cmd = pidof hyprlock || hyprlock --immediate-render
    before_sleep_cmd = hypr-prepare-for-sleep
    after_sleep_cmd = hypr-lock-after-sleep
}

listener {
    timeout = 86400
    on-timeout = loginctl lock-session
}
